on:
  push: {}

jobs:
  ci:
    runs-on: shell
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate Dagger code
        run: ./ci/develop.sh

      #- name: Run dagger pipeline
      #  run: dagger --progress plain call run
