name: Test Modules

on: [push, pull_request]

jobs:
  test_modules:
    name: Test Modules
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Test and Lint
        uses: dagger/dagger-for-github@v8.4.1
        with:
          version: "latest"
          verb: call
          # args: run
          args: test
          cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
