name: CI

on: [push, pull_request]

jobs:
  ci:
    name: Lint and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Setup Dagger
        uses: dagger/dagger-for-github@v8.4.1
        with:
          version: "latest"
          cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}

      - name: Generate Dagger code
        run: ./ci/develop.sh

      - name: Lint
        run: dagger call lint --source=.

      - name: Test
        run: dagger call test
