name: CI

on: [push]

jobs:
  ci:
    name: Lint and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Setup Dagger
        uses: dagger/dagger-for-github@v8.4.1
        with:
          version: "latest"
          cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}

      - name: Generate Dagger code
        run: |
          dagger develop

          for dir in go bun rust merge-dirs; do
            cd "$dir"
            dagger develop
            cd -

            if [ -d "$dir/tests" ]; then
              cd "$dir/tests"
              dagger develop
              cd -
            fi
          done

      - name: Run Pipeline
        run: dagger call all
